config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  get 'bookings/:id/accept', to: 'bookings#accept', as: 'accept_booking'
  get 'bookings/:id/decline', to: 'bookings#decline', as: 'decline_booking'
  resources :yachts do
    resources :toys, only: [:create]
    resources :bookings, only: [:create, :index]
    resources :reviews, only: :create
  end
  resources :bookings, only: [:destroy]
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :yacht
  belongs_to :user
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :yacht
  belongs_to :user
  validates :rating, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :yachts, dependent: :destroy
  has_many :reviews
  has_many :bookings
  validates :username, uniqueness: { case_sensitive: false }
  validates :email, format: { with: /\b[\w\.-]+@[\w\.-]+\.\w{2,4}\b/ }
  validates :password, length: { in: 6..20 }
end

app/models/yacht.rb
class Yacht < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews, dependent: :destroy
  has_many_attached :photos

  validates :title, presence: true, uniqueness: true
  validates :build, presence: true
  validates :address, presence: true
  validates :description, length: { minimum: 20 }
  validates :year, numericality: { only_integer: true }
  validates :weekly_price, numericality: { only_integer: true }
  validates :length, numericality: { only_integer: true }
  validates :beam, numericality: { only_integer: true }
  validates :cruising_speed, numericality: { only_integer: true }
  validates :number_of_crew, numericality: { only_integer: true }
  validates :number_of_guests, numericality: { only_integer: true }
  validates :number_of_cabins, numericality: { only_integer: true }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def self.fetch_toys_for_yacht
    toys = %w(Jetski Scuba BananaBoat Snorkels Harpoon Helicopter)
    result = []
    toys.each { |toy| result << [toy, toy]}
    result
  end
  include PgSearch::Model
  pg_search_scope :search_by_title_and_description,
    against: [ :title, :description, :address ],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @yacht = Yacht.find(params[:yacht_id])
    @bookings = Booking.where(yacht_id: params[:yacht_id])
  end

  def create
    @booking = Booking.new(booking_params)
    # we need `yacht_id` to associate booking with corresponding yacht
    @yacht = Yacht.find(params[:yacht_id])
    @booking.yacht = @yacht
    @booking.user = current_user
    @booking.accepted = false
    if @booking.save # ensures validations pass
      redirect_to dashboard_path
    else
      redirect_to yacht_path(@yacht.id)
    end
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.accepted = true
    @booking.save
    redirect_to dashboard_path
  end

  def decline
    @booking = Booking.find(params[:id])
    @booking.accepted = false
    @booking.save
    redirect_to dashboard_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.delete
    redirect_to dashboard_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :configure_permitted_parameters, only: :home
  def home
    @top_rated = Yacht.order(average_rating: :desc).limit(3)
  end

  def dashboard
    @yachts = Yacht.where(user: current_user)
    @bookings = Booking.where(user: current_user)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @yacht = Yacht.find(params[:yacht_id])
    @review.yacht = @yacht
    @review.user = current_user
    if @review.save!
      redirect_to yacht_path(@yacht.id, anchor: "review-#{@review.id}")
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.delete
    redirect_to yacht_path(@review.yacht.id)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/yachts_controller.rb
class YachtsController < ApplicationController
  skip_before_action :configure_permitted_parameters, only: [:index, :show]

  def index

    if params[:query].present?
      @yachts = Yacht.search_by_title_and_description(params[:query])
    else
      @yachts = Yacht.all
    end
    @markers = @yachts.geocoded.map do |yacht|
      {
        lat: yacht.latitude,
        lng: yacht.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { yacht: yacht }),
        image_url: helpers.asset_url('ly_map_pin.png'),
        yachtId: yacht.id
      }
    end
  end

  def new
    @yacht = Yacht.new
  end

  def show
    id = params[:id]
    @yacht = Yacht.find(id)
    @photos = @yacht.photos
    @booking = Booking.new
    @markers = [
      {
        lat: @yacht.latitude,
        lng: @yacht.longitude,
        image_url: helpers.asset_url('ly_map_pin.png'),
        yachtId: @yacht.id
      }
    ]
    @review = Review.new
  end

  def create
    # byebug
    @yacht = Yacht.new(yacht_params)
    @yacht.toys = join_toys
    @yacht.user = current_user
    if @yacht.save # ensures validations pass
      redirect_to yacht_path(@yacht.id)
    else
      render :new
    end
  end

  def edit
    @yacht = Yacht.find(params[:id])
  end

  def update
    @yacht = Yacht.find(params[:id])
    @yacht.update(yacht_params)
    if @yacht.save
      redirect_to yacht_path(@yacht.id)
    else
      render :edit
    end
  end

  def destroy
    @yacht = Yacht.find(params[:id])
    @yacht.destroy
    redirect_to dashboard_path
  end

  private

  def yacht_params
    params.require(:yacht).permit(:title, :description, :weekly_price, :address,
                                  :length, :number_of_crew, :number_of_guests,
                                  :number_of_cabins, :beam, :cruising_speed, :build, :year, :toys, photos: [])
  end

  def join_toys
    toys = params.require(:yacht).require(:toys)
    toys.shift
    return toys.join(", ")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/index.html.erb
<h1 class="text-center mt-3">Enquires for <%= @yacht.title %></h1>
<% if @bookings.any? %>
  <div class="container d-flex mt-2">
    <% @bookings.each do |booking| %>
      <div class="card text-center" style="width: 400px">
        <div class="card-body">
          <h3 class="card-title">Enquiry for <%= booking.yacht.title %></h3>
          <h6 class="card-title">Enquiry from: <%= booking.user.username || booking.user.email %></h6>
          <h6 class="card-subtitle mb-2 mt-2 text-muted">Start Date: <%= booking.start_date.strftime('%A %d %b %Y') %></h6>
          <h6 class="card-subtitle mb-2 mt-2 text-muted">End Date: <%= booking.end_date.strftime('%A %d %b %Y') %></h6>
          <% if booking.accepted == true %>
            <h4><span class="badge badge-success my-2">Booking Confirmed!</span></h4>
          <% else %>
            <h4><span class="badge badge-warning my-2">Booking awaiting confirmation.</span></h4>
          <% end %>
          <p class="mt-2"><%= link_to "Accept", accept_booking_path(booking), class: 'create-btn' %>
          <%= link_to "Decline", decline_booking_path(booking), class: 'create-btn' %></p>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <h3 class="text-center mt-5">There are currently no enquiries for <%= @yacht.title %></h3>
<% end %>
<h4 class="text-center mt-3"><%= link_to 'Back to Dashboard', dashboard_path, class: 'create-btn' %></h4>

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>
<p>Find me in app/views/bookings/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lilyachties</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div style="height: 60px;"></div>
    <%= render 'shared/flashes' %>
    <div class="application-container" style="min-height: calc(100vh - 120px);">
          <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
  <h1 class="text-center">Welcome to your Dashboard</h1>
  <div class="content d-flex">
    <div class="dashboard-bookings w-50">
      <h4 class="text-center">Your bookings</h4>
      <% if @bookings.count > 0 %>
        <% @bookings.each do |booking| %>
          <div class="card text-center m-3">
            <div class="card-body">
              <h3 class="card-title">Your booking on board <%= booking.yacht.title %></h3>
              <h6 class="card-subtitle mb-2 text-muted">Start Date: <%= booking.start_date.strftime('%A %d %b %Y') %></h6>
              <h6 class="card-subtitle mb-2 text-muted">End Date: <%= booking.end_date.strftime('%A %d %b %Y') %></h6>
              <% if booking.accepted == true %>
                <h4><span class="badge badge-success my-2">Booking Confirmed!</span></h4>
              <% else %>
               <h4><span class="badge badge-warning my-2">Booking awaiting confirmation.</span></h4>
              <% end %>
              <p class="mt-2"><%= link_to "View Yacht", yacht_path(booking.yacht.id), class: 'create-btn' %>
              <%= link_to "Cancel Booking", booking_path(booking), method: :delete, data: { confirm: 'Are you sure?' }, class: 'create-btn' %></p>
            </div>
          </div>
        <% end %>
      <% else %>
        <p>It looks like you don't have any bookings yet, what are you waiting for?</p>
      <% end %>
    </div>
    <div class="dashboard-yachts w-50">
      <h4 class="text-center">Your Yachts</h4>
      <div class="yachts d-flex flex-wrap justify-content-center">
        <% @yachts.each do |yacht| %>
          <div class="yacht mb-3">
            <%= render 'shared/yacht_card', yacht: yacht, margin: 20 %>
            <p class="text-center"><%= link_to 'View Enquiries', yacht_bookings_path(yacht), class: 'create-btn' %></p>
            <p class="text-center"><%= link_to 'Edit', edit_yacht_path(yacht), class: 'create-btn' %>
            <%= link_to 'Delete', yacht_path(yacht), method: :delete, data: { confirm: 'Are you sure?' }, class: 'create-btn' %></p>
          </div>
        <% end %>
      </div>
      <p class="text-center">
        <%= link_to 'Add a New Yacht', new_yacht_path, class: 'create-btn' %>
      </p>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>
<div class="home-background">
  <div class="top-rated-carousel">
    <div class="home-tr-text" style="margin: 0 auto">
      <h1 class="home-tr">Top rated:</h1>
      <h2 class="home-tr-sub">&nbsp;&nbsp;&nbsp;WINTER 2020</h2>
    </div>
    <% unless @top_rated.nil? %>
      <% @top_rated.each do |yacht| %>
        <%= render 'shared/yacht_card', yacht: yacht, margin: 5 %>
      <% end %>
    <% end %>
  </div>
  <div class="home-grey">

  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="banner-container"></div>
  <div class="banner-content">
    <h1>Find your perfect<br>yacht holiday.</h1>
    <%= link_to 'Explore', yachts_path, class: "btn btn-light", style: "color: #284B63; background-color: #D9D9D9; padding-left: 20px; padding-right: 20px; border: 0;" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<nav class="navbar justify-flex-start footer">
  <div class="links d-flex">
    <a class="nav-link" href="#">Contact us</a>
    <a class="nav-link" href="#">Terms</a>
    <a class="nav-link" href="#">Privacy</a>
  </div>
  <div class="socials d-flex">
    <a href="#"><i class="fab fa-facebook-square m-2 social"></i></a>
    <a href="#"><i class="fab fa-instagram-square m-2 social"></i></a>
    <a href="#"><i class="fab fa-twitter-square m-2 social"></i></a>
  </div>
  <div class="made-by">
    <h6 class="navbar-brand made-by">Made by: Team Piatto</h6>
  </div>
</nav>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon p-0" style="height: 60px; box-shadow: 0px 15px 30px rgba(0, 0, 0, 0.1);">
  <%= link_to image_tag("lylogo.png", style: 'height: 100%; padding: 0; margin: 0;'), root_path, style: 'height: 100%; padding: 0; margin: 0;' %>
  <button class="navbar-toggler mr-3 " type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto align-items-center">
      <li class="nav-item m-3 pl-3 pr-3 <%= 'active' if request.path == '/' %> " style="background-color: white;">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <!--  -->

        <%= current_user ? link_to((current_user.username || current_user.email), '#', class: "nav-item dropdown-toggle m-3", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) : link_to('Log in', new_user_session_path, class: 'btn btn-outline-dark m-3') %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_yacht_card.html.erb
<div class="yc-container" style="margin: 0 auto;">
  <div class="yacht-card" style="margin: 10px;">
    <div class="yc-image-holder">
      <%= link_to yacht_path(yacht.id) do %>
        <% if yacht.photos[0] %>
          <div class="yc-image" style='background-image: url("<%= cl_image_path yacht.photos[0].key%>");'></div>
        <% else %>
          <div class="yc-image" style='background-image: none'></div>
        <% end %>
      <% end %>
     <div class="yc-yacht-name"><%= yacht.title %></div>
    </div>
    <div class="yc-info">
      <div class="yc-details p-1">
        <div class="location-guests">
          <div class="yc-location" style="font-size: 14px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;"><i class="fas fa-map-pin icon text-center"></i> <%= yacht.address %></div>
          <div class="yc-guests" style="font-size: 14px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;"><i class="fas fa-users icon text-center"></i> <%= yacht.number_of_guests %></div>
        </div>
        <div class="rating-price">
          <div class="yc-price" style="font-size: 14px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">€<%= yacht.weekly_price %>p/w</div>
          <div class="yc-rating" style="font-size: 14px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;"><%= yacht.average_rating.nil? ? 'No ratings' : '⭑' * yacht.average_rating %></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/yachts/_form.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-6">
      <%= simple_form_for @yacht do |f| %>
        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.input :weekly_price %>
        <%= f.input :length %>
        <%= f.input :beam %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      </div>
      <div class="col-6">
        <%= f.input :build %>
        <%= f.input :cruising_speed %>
        <%= f.input :address %>
        <%= f.input :number_of_guests %>
        <%= f.input :number_of_crew %>
        <%= f.input :number_of_cabins %>
      </div>
      <%= f.submit class: "create-btn mr-4"%>
    <% end %>
    <%= link_to "Back", yachts_path, class: "create-btn" %>
  </div>
</div>

app/views/yachts/_images.html.erb
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= cl_image_tag @yacht.photos[0].key, height: 600, style:"object-fit:cover;", class: 'd-block w-100' %>
    </div>
    <% @yacht.photos.each do |photo| %>
      <% photo_index = @yacht.photos.index(photo) %>
      <% unless photo_index == 0 %>
        <div class="carousel-item">
          <%= cl_image_tag @yacht.photos[photo_index].key, height: 600, style:"object-fit:cover;", class: 'd-block w-100' %>
        </div>
      <% end %>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/yachts/_info_window.html.erb
<h2 style='font-weight: bolder; font-size: 18px;'><%= yacht.title %></h2>
<p><%= yacht.address %></p>
<%= link_to cl_image_tag(yacht.photos[0].key, style: 'border-radius: 10px; width: 150px;'), yacht_path(yacht) if yacht.photos[0] %>

app/views/yachts/_review.html.erb
<div class="container p-0">
  <div class="row d-flex-justify-space-between">
    <div class="container box col-6 pr-0" id="reviews">
      <div class="list-group list-reviews">
        <% @yacht.reviews.each do |review| %>
          <p id="review-<%= review.id %>"></p>
            <li class="list-group-item reviews mb-2">
              <%= review.user.username || review.user.email %>
                <% if review.user == current_user %>
                  <%= link_to review_path(review),
                    method: :delete,
                    data: { confirm: "Are you sure?" } do %>
                    <i class="fas fa-trash-alt"></i>
                  <% end %>
                <% end %>
                <small>
                  <% review.rating.times do %>
                    <i class="fas fa-star"></i>
                  <% end %>

                </small>
                <p><%= review.content %></p>
            </li>
        <% end %>
      </div>
    </div>
    <div class="container box col-6 pr-0">
      <% if @yacht.user != current_user && current_user && @yacht.bookings.pluck(:user_id).include?(current_user.id) && @yacht.reviews.pluck(:user_id).none?(current_user.id) %>
        <div id="form-width">
          <%= simple_form_for [@yacht, @review], remote: true do |f| %>
            <%= f.input :rating, collection: 1..5 %>
            <%= f.input :content %>
            <div class="btn-width mx-auto">
              <%= f.submit class: "create-btn button-center" %>
            </div>
          <% end %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/yachts/edit.html.erb
<h1>Edit Yacht</h1>
  <div class="container py-5">
    <%= simple_form_for @yacht do |f| %>
      <div class="row">
        <div class="col-6">
          <%= f.error_notification %>
          <%= f.input :title %>
          <%= f.input :description %>
          <%= f.input :weekly_price %>
          <%= f.input :length %>
          <%= f.input :beam %>
          <%= f.input :year %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <%=  f.collection_check_boxes :toys, Yacht.fetch_toys_for_yacht, :first, :last %>
        </div>
        <div class="col-6">
          <%= f.input :build %>
          <%= f.input :cruising_speed %>
          <%= f.input :address %>
          <%= f.input :number_of_guests %>
          <%= f.input :number_of_crew %>
          <%= f.input :number_of_cabins %>
        </div>
      <%= f.submit 'Update', class: "create-btn mr-4"%>
    <% end %>
    <%= link_to "Back", dashboard_path, class: "create-btn" %>
  </div>
</div>

app/views/yachts/index.html.erb
<h1 class="text-center">Choose your Lil' Yacht</h1>
<div class="container">
  <%= form_tag yachts_path, method: :get, class: "center-form" do %>
    <%= text_field_tag :query, params[:query], class: "form-control search", placeholder:"Search e.g. Name, Description or Price" %>
  <% end %>
  <div>
    <div class="row">
      <div class="col-8" style="width: 75vw">
        <div class="index-cards">
          <% @yachts.each do |yacht| %>
            <%= render 'shared/yacht_card', yacht: yacht, margin: 30 %>
          <% end %>
        </div>
      </div>
      <div class="col-4" style="width: 25vw">
        <div id="map" style="border-radius: 14px; width: 100%; height: 100%; margin-top: 20px; top: 0; bottom: 0; position: absolute;"
         data-markers="<%= @markers.to_json %>"
         data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/yachts/new.html.erb
<h1>Add A New Yacht Listing</h1>
  <div class="container py-5">
    <%= simple_form_for @yacht do |f| %>
      <div class="row">
        <div class="col-6">
          <%= f.error_notification %>
          <%= f.input :title %>
          <%= f.input :description %>
          <%= f.input :weekly_price %>
          <%= f.input :length %>
          <%= f.input :beam %>
          <%= f.input :year %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <%=  f.collection_check_boxes :toys, Yacht.fetch_toys_for_yacht, :first, :last %>
        </div>
        <div class="col-6">
          <%= f.input :build %>
          <%= f.input :cruising_speed %>
          <%= f.input :address %>
          <%= f.input :number_of_guests %>
          <%= f.input :number_of_crew %>
          <%= f.input :number_of_cabins %>
        </div>
      <%= f.submit 'Create', class: "create-btn"%>
    <% end %>
    <%= link_to "Back", dashboard_path, class: "create-btn" %>
  </div>
</div>